### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by untereiner** [F2I-Consulting/fesapi#346]
# What are the steps to reproduce this issue?
1. git clone
2. cmake build with g++ (GCC) 14.1.1 20240522

# What does happen?

```shell
/home/fesapi-superbuild/build/release-gcc/_deps/fesapi-src/src/resqml2/IjkGridParametricRepresentation.cpp: In member function ‘void resqml2::IjkGridParametricRepresentation::getXyzPointsAlongACoordinateLine(uint64_t, uint64_t, uint64_t, uint64_t, const double*, double*) const’:
/home/fesapi-superbuild/build/release-gcc/_deps/fesapi-src/src/resqml2/IjkGridParametricRepresentation.cpp:437:30: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’?
  437 |                         std::memcpy(xyzPoints + xPointIndex, pillarInformation->controlPoints.get() + pillarXIndex, 2 * sizeof(double));
      |                              ^~~~~~
      |                              wmemcpy
```

# What were you expecting to happen?

no compilation error
suggestion:` include <cstring>` in `IjkGridParametricRepresentation.cpp`

# Any logs, error output, etc?
n.a.

# Any other comments?
n.a.

# What versions of fesapi are you using?
n.a.

**Comment by philippeVerney** [comment]
Hi Lionel,
I think it is only on the dev branch.
As this branch is close to become the v2.10, i am happy you rise this issue now. Thanks!

**Comment by untereiner** [comment]
Hi @philippeVerney, yes on the dev branch !
